feat: enforce manifest name to be equal to artifact name
The server enforces that the `name` field in the Manifest must be equal
to the `artifact_name` in the Manifest Artifact.

Ticket: MEN-10212
Changelog: Title

Signed-off-by: Daniel Skinstad Drabitzius <daniel.drabitzius@northern.tech>

diff --git a/modules/mender-orchestrator-manifest/module-artifact-gen/mender-orchestrator-manifest-gen b/modules/mender-orchestrator-manifest/module-artifact-gen/mender-orchestrator-manifest-gen
--- a/modules/mender-orchestrator-manifest/module-artifact-gen/mender-orchestrator-manifest-gen
+++ b/modules/mender-orchestrator-manifest/module-artifact-gen/mender-orchestrator-manifest-gen
@@ -185,6 +185,13 @@ echo -n $passthrough_args | xargs -n 2 printf "%s %s\n" | (while read -r flag ar
     fi
 done
 
+# Ensure 'name' in the manifest equals `artifact_name` in the artifact
+manifest_name=$(yq -r '.name // ""' "$manifest_file")
+if [ "$manifest_name" != "$artifact_name" ]; then
+    echo "Error: manifest 'name' ('${manifest_name}') must be equal to the artifact name ('${artifact_name}')" 1>&2
+    exit 1
+fi
+
 mender-artifact write module-image \
     --type mender-orchestrator-manifest \
     $system_types \
