feat: component identity
Ticket: MEN-8535
Changelog: Add identity state to update interfaces. Small Cleanup.

Signed-off-by: Michal Kopczan <michal.kopczan@northern.tech>

diff --git a/interfaces/v1/rootfs-image b/interfaces/v1/rootfs-image
--- a/interfaces/v1/rootfs-image
+++ b/interfaces/v1/rootfs-image
@@ -18,7 +18,6 @@ set -e
 STATE="$1"
 FILES="$2"
 COMPONENT_TYPE="$3"
-COMPONENT_ID="$4"
 
 case "$STATE" in
     NeedsArtifactReboot)
@@ -110,4 +109,11 @@ case "$STATE" in
         mender-update show-provides
         ;;
 
+    Identity)
+        if [ "$STATE" = "Identity" ]; then
+            [ -f "$INSTANCE_DIR/$STATE.FAIL" ] && { log "Failing $STATE"; exit 1; }
+            id=$(/usr/share/mender/identity/mender-device-identity | sed -n 's/^mac=//p')
+            echo "id=$id"
+        fi
+        ;;
 esac
